metadata:
  name: ${project.artifactId}
  annotations:
    api.service.kubernetes.io/path: /
    service.beta.kubernetes.io/azure-load-balancer-internal: "${azure.expose-to-vnet}"
spec:
  type: ${fabric8.service.type}
  ports:
  - port: ${tcp.port.exposed}
    protocol: TCP
    targetPort: ${tcp.port.internal}
    name: ms-port
  selector:
    app: ${project.artifactId}